theme: jekyll-theme-cayman

# Site settings
title: Shadow Yuan Zone                    # 你的博客网站标题
SEOTitle: 袁钰涛的博客 | Shadow Yuan Blog	 # SEO 标题
description: "Hey"	   	                 # 随便说点，描述一下

# SNS settings      
github_username: shadowyuan616               # 你的github账号

# Build settings
# paginate: 10                           # 一页你准备放几篇文章
