theme: jekyll-theme-minimal

# Site settings
title: Shadow Yuan Zone                    # 你的博客网站标题
SEOTitle: 袁钰涛的博客 | Shadow Yuan Blog	 # SEO 标题
description: "< 崇尚科学 志存高远 不尚浮华 >"	   	                 # 随便说点，描述一下

# SNS settings      
github_username: shadowyuan616               # 你的github账号

# Build settings
# paginate: 10                           # 一页你准备放几篇文章

logo: /img/Shadow Yuan with camera.jpg   # 你的大头贴，请使用绝对地址.注意：名字区分大小写！后缀名也是
