# 用于构建和部署 Jekyll 网站到 GitHub Pages 的示例工作流
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # 在向默认分支（main）推送时运行
  push:
    branches: ["main"]

  # 允许您从 Actions 标签页手动运行此工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署，跳过在进行中和最新排队之间的运行。
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成。
concurrency:
  group: "pages"
  cancel-in-progress: false # 从 true 改为 false，这是目前的推荐设置

jobs:
  # 由于我们只是部署，因此使用单个部署作业
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # 从 v3 更新
      - name: Setup Pages
        uses: actions/configure-pages@v5 # 从 v2 更新
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1 # 此 Action 目前仍是 v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # 从 v1 更新
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # 从 v1 更新
